-- MySQL Script generated by MySQL Workbench
-- mié 15 abr 2020 16:52:04 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BANCO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BANCO` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BANCO` ;

-- -----------------------------------------------------
-- Table `BANCO`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BANCO`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `BANCO`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(10) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`Cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BANCO`.`Cuentas` ;

CREATE TABLE IF NOT EXISTS `BANCO`.`Cuentas` (
  `idCuentas` INT NOT NULL AUTO_INCREMENT,
  `Balance` DOUBLE NOT NULL,
  `IDCliente` INT NOT NULL,
  PRIMARY KEY (`idCuentas`),
  INDEX `IDCliente_idx` (`IDCliente` ASC),
  CONSTRAINT `IDCliente`
    FOREIGN KEY (`IDCliente`)
    REFERENCES `BANCO`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
	CHECK(idCuentas>=0)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`TipoTransf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BANCO`.`TipoTransf` ;

CREATE TABLE IF NOT EXISTS `BANCO`.`TipoTransf` (
  `idTipoTransf` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoTransf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`Transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BANCO`.`Transacciones` ;

CREATE TABLE IF NOT EXISTS `BANCO`.`Transacciones` (
  `idTransacciones` INT NOT NULL AUTO_INCREMENT,
  `Importe` DOUBLE NOT NULL,
  `IDCuenta` INT NULL,
  `IDTipoTransf` INT NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTransacciones`),
  INDEX `IDCuenta_idx` (`IDCuenta` ASC),
  INDEX `IDTipoTransf_idx` (`IDTipoTransf` ASC),
  CONSTRAINT `IDCuenta`
    FOREIGN KEY (`IDCuenta`)
    REFERENCES `BANCO`.`Cuentas` (`idCuentas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IDTipoTransf`
    FOREIGN KEY (`IDTipoTransf`)
    REFERENCES `BANCO`.`TipoTransf` (`idTipoTransf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO TipoTransf (idTipoTransf, Descripcion)
	VALUES 
		(1,'Transferencia'),
		(2,'Retirada');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


